blueprint:
  name: Set Indicator Light for SWITCH on Scene Controller with State Overwrite
  description: For Zooz ZEN32. Sets the indicator color when switch is off or on.
  domain: automation
  input:
    zooz_switch:
      name: Zooz Switch
      description: List of available Zooz ZEN32 switches.
      selector:
        device:
          integration: zwave_js
          manufacturer: Zooz
          model: ZEN32
          multiple: false
    target_light:
      name: Switch
      description: The switch to link to button
      selector:
        entity:
          domain: switch
          multiple: false
    scene_button:
      name: Scene Button
      description: The button to link to light
      selector:
        select:
          mode: dropdown
          options:
          - label: Scene 5 (Big Button)
            value: '0'
          - label: Scene 1 (Top Left)
            value: '1'
          - label: Scene 2 (Top Right)
            value: '2'
          - label: Scene 3 (Bottom Left)
            value: '3'
          - label: Scene 4 (Bottom Right)
            value: '4'
          multiple: false
          custom_value: false
    off_state:
      name: Off State
      description: Led state when light is off
      default: Led On
      selector:
        select:
          mode: dropdown
          options:
          - label: Led On
            value: '3'
          - label: Led Off
            value: '2'
          multiple: false
          custom_value: false
    off_color:
      name: State Off Color
      description: Color for led when switch is off (default white)
      default: White
      selector:
        select:
          mode: dropdown
          options:
          - label: White
            value: '0'
          - label: Blue
            value: '1'
          - label: Green
            value: '2'
          - label: Red
            value: '3'
          multiple: false
          custom_value: false
    on_state:
      name: On State
      description: Led state when light is On
      default: Led On
      selector:
        select:
          mode: dropdown
          options:
          - label: Led On
            value: '3'
          - label: Led Off
            value: '2'
          multiple: false
          custom_value: false
    on_color:
      name: State On Color
      description: Color for led when switch is on (default white)
      default: White
      selector:
        select:
          mode: dropdown
          options:
          - label: White
            value: '0'
          - label: Blue
            value: '1'
          - label: Green
            value: '2'
          - label: Red
            value: '3'
          multiple: false
          custom_value: false
  source_url: https://gist.github.com/sle118/f4663622f210ecf6f11ba903d4e6aef9
mode: single
max_exceeded: silent
variables:
  controller_id: !input zooz_switch
  light_id: !input target_light
  button_id: !input scene_button
  toggle_offset: 1
  color_offset: 6
  on_state: !input on_state
  on_color: !input on_color
  off_state: !input off_state
  off_color: !input off_color
trigger:
- platform: state
  entity_id: !input target_light
action:
- choose:
  - conditions: '{{ is_state(light_id, ''off'') }}'
    sequence:
    - parallel:
      - service: zwave_js.set_config_parameter
        data:
          parameter: '{{ (button_id | int) + (color_offset | int) }}'
          value: '{{ off_color }}'
        target:
          device_id: '{{ controller_id }}'
      - service: zwave_js.set_config_parameter
        data:
          parameter: '{{ (button_id | int) + (toggle_offset | int) }}'
          value: '{{ off_state }}'
        target:
          device_id: '{{ controller_id }}'
  - conditions: '{{ is_state(light_id, ''on'') }}'
    sequence:
    - parallel:
      - service: zwave_js.set_config_parameter
        data:
          parameter: '{{ (button_id | int) + (color_offset | int) }}'
          value: '{{ on_color }}'
        target:
          device_id: '{{ controller_id }}'
      - service: zwave_js.set_config_parameter
        data:
          parameter: '{{ (button_id | int) + (toggle_offset | int) }}'
          value: '{{ on_state }}'
        target:
          device_id: '{{ controller_id }}'
